#! /bin/bash
unset DISPLAY

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Checking for updates. This might take a while..."
java -Dsilent=true -jar "$DIR/../launch/getdown-client.jar" "$DIR/../launch"

export X509_USER_PROXY="$HOME/.grid/grid.proxy"
#export JAVA_OPTS="-Djava.awt.headless=true -Xms64m -Xmx64m"

# check whether we have our own jvm
if [ -f "$DIR/../launch/java_vm/bin/java" ]
then
   "$DIR/../launch/java_vm/bin/java" ${JAVA_OPTS} -cp "$DIR/../launch/grid-client-core.jar:$DIR/../launch/grid-client-dependencies.jar" grisu.gricli.Gricli $@
else
   java ${JAVA_OPTS} -cp "$DIR/../launch/grid-client-core.jar:$DIR/../launch/grid-client-dependencies.jar" grisu.gricli.Gricli $@
fi

