#! /bin/bash
unset DISPLAY

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Checking for updates. This might take a while..."
java -Dsilent=true -jar "$DIR/../launch/getdown-client.jar" "$DIR/../launch"

export X509_USER_PROXY="$HOME/.grid/grid.proxy"
export JAVA_OPTS="-Djava.awt.headless=true -Xms64m -Xmx64m"

java ${JAVA_OPTS} -cp "$DIR/../launch/combinedClient-binary.jar" grisu.gricli.Gricli $@
