#!/bin/bash

#unset DISPLAY

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Checking for updates. This might take a while..."
java -Dsilent=true -jar "$DIR/../launch/getdown-client.jar" "$DIR/../launch"

#export JAVA_OPTS="-Djava.awt.headless=true -Xms128m -Xmx128m"
export JAVA_OPTS="-Djava.awt.headless=true"

export X509_USER_PROXY=~/.grid/grid.proxy
java ${JAVA_OPTS} -cp "$DIR/../launch/grid-client-core.jar:$DIR/../launch/grid-client-dependencies.jar" grisu.Grython $@


