#!/bin/sh

APPDIR="$HOME/Library/Application Support/NeSI/"

#DIR=$(cd "$(dirname "$0")"; pwd)
DIR=/Library/Frameworks/NeSI/

if [ ! -d "$APPDIR" ]
then
  mkdir -p "$APPDIR"
fi

if [ ! -f "$APPDIR/getdown.txt" ] 
then 
	cp "$DIR/resources/getdown.txt" "$APPDIR"
fi

if [ ! -f "$APPDIR/grisu.png" ] 
then 
	cp "$DIR/resources/grisu.png" "$APPDIR"
fi

if [ ! -f "$APPDIR/combinedClient-binary.jar" ] 
then 
	cp "$DIR/launch/combinedClient-binary.jar" "$APPDIR"
fi


export X509_USER_PROXY="$HOME/.grid/grid.proxy"
java -jar "$DIR/launch/getdown-client.jar" "$APPDIR" tray

